### ISSUE TITLE
createReadStream() fails with REQUEST_CANCELLED after clear

### ISSUE THREAD

**Issue by MKPLKN** [holepunchto/hypercore#460]
**Description**
When `hypercore.createReadStream()` is called after the hypercore has been cleared, it throws a `HypercoreError: REQUEST_CANCELLED`

**Steps to Reproduce**
1. Create a Hypercore instance and append some data, for example, `core.append([1,2,3,4])`.
2. Clear the hypercore, for example, `core.clear(1,2)`.
3. Attempt to create a read stream from the hypercore, `core.createReadStream()`.
4. the `REQUEST_CANCELLED` error is thrown.

```javascript
HypercoreError: REQUEST_CANCELLED: Request was cancelled
    at BlockRequest._cancel (/node_modules/hypercore/lib/replicator.js:79:21)
    at BlockRequest.detach (/node_modules/hypercore/lib/replicator.js:55:10)
    at Replicator.clearRequests (/node_modules/hypercore/lib/replicator.js:1405:19)
    at Hypercore._close (/node_modules/hypercore/index.js:462:23)
    at Hypercore.close (/node_modules/hypercore/index.js:438:25)
    at Object.fn (file:///src/utils/cores.js:50:22)
    at run (/node_modules/graceful-goodbye/index.js:51:13)
    at Array.map (<anonymous>)
    at loop (/node_modules/graceful-goodbye/index.js:41:36)
    at process.onexit (/node_modules/graceful-goodbye/index.js:37:3) {
  code: 'REQUEST_CANCELLED'
}
```

**Environment**
- Hypercore version: 10.31.9
- Node.js version: 16.14.2

**Comment by MKPLKN** [comment]
Note, you do not get the `REQUEST_CANCELLED` error without `goodbye(() => core.close())`

Anyway, the main issue is that the read stream stops at the first cleared value and doesn't continue to read the rest of the core.

**Comment by mafintosh** [comment]
i think this is working as expected. the readstreams waits for the blocks to arrive - you deleted the block so its waiting for someone to give it to you.

**Comment by MKPLKN** [comment]
> you deleted the block so its waiting for someone to give it to you.

Makes a lot of sense and explains the behaviour.

If we set the `wait` option to `false`, shouldn't the stream continue then?

**Comment by MKPLKN** [comment]
Something along these lines?

```javascript
const v = await this.core.get(this.start++, { wait: this.core.wait });

if (this.core.wait === false && !v) {
  this._readP();
} else {
  this.push(v);
}
```
